// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// parse_pgn
bool parse_pgn(std::string in_path, std::string out_path, std::string log_path);
RcppExport SEXP _pigeon_parse_pgn(SEXP in_pathSEXP, SEXP out_pathSEXP, SEXP log_pathSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::string >::type in_path(in_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type out_path(out_pathSEXP);
    Rcpp::traits::input_parameter< std::string >::type log_path(log_pathSEXP);
    rcpp_result_gen = Rcpp::wrap(parse_pgn(in_path, out_path, log_path));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pigeon_parse_pgn", (DL_FUNC) &_pigeon_parse_pgn, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_pigeon(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
