# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

parse_pgn <- function(in_path, out_path, log_path) {
    .Call('_pigeon_parse_pgn', PACKAGE = 'pigeon', in_path, out_path, log_path)
}

