# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

int_pgn_count <- function(path) {
    .Call('_pigeon_int_pgn_count', PACKAGE = 'pigeon', path)
}

int_pgn_recs <- function(path, v) {
    .Call('_pigeon_int_pgn_recs', PACKAGE = 'pigeon', path, v)
}

int_pgn_iter <- function(path, f) {
    invisible(.Call('_pigeon_int_pgn_iter', PACKAGE = 'pigeon', path, f))
}

